name: Tuya
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas=2.1.4
  - numpy=1.26.4
  - matplotlib=3.7.3
  - scikit-learn=1.4.2
  - scipy=1.11.4
  - prophet=1.1.1
  - pip:
    - prophet==1.1.7
    - statsmodels==0.14.4
    - joblib==1.3.2
    - pmdarima==2.0.4
    - seaborn==0.13.2
    - holidays==0.24
    - jupyterlab
